### ISSUE TITLE
Build fails on Ubuntu [FFTW Error] 

### ISSUE THREAD

**Issue by shaheenkdr** [facebookresearch/wav2letter#104]
trying to build `wav2letter` on Ubuntu, when I execute : 

`cmake .. -DCMAKE_BUILD_TYPE=Release -DCRITERION_BACKEND=CUDA -DArrayFire_DIR=/opt/arrayfire-no-gl/share/ArrayFire/cmake/
`

I get the error : 

```
-- GTest found (library: /usr/lib/libgtest.a include: /usr/include)
-- ArrayFire found (include: /opt/arrayfire-no-gl/include, library: ArrayFire::afcuda)
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- GLOG found
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- GFLAGS found
-- OpenMP found
flashlight found (include:  lib: flashlight::flashlight )
-- flashlight built in distributed mode.
-- Checking for [mkl_gf_lp64 - mkl_gnu_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_gf_lp64: /root/anaconda2/envs/fbresearch/lib/libmkl_gf_lp64.so
--   Library mkl_gnu_thread: /root/anaconda2/envs/fbresearch/lib/libmkl_gnu_thread.so
--   Library mkl_core: /root/anaconda2/envs/fbresearch/lib/libmkl_core.so
--   Library iomp5: /root/anaconda2/envs/fbresearch/lib/libiomp5.so
--   Library pthread: /usr/lib/x86_64-linux-gnu/libpthread.so
--   Library m: /usr/lib/x86_64-linux-gnu/libm.so
-- MKL library found
-- MKL found
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find FFTW (missing: FFTW_LIBRARIES)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindFFTW.cmake:94 (find_package_handle_standard_args)
  src/feature/CMakeLists.txt:13 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/wav2letter/build/CMakeFiles/CMakeOutput.log".
See also "/home/wav2letter/build/CMakeFiles/CMakeError.log".
```

I manually installed `FFTW` before starting to build `wav2letter`  and the manual build was in `/opt/fftw3` . 

When the build failed with the aforementioned error, based on the other issues, I also tried installing `FFTW` using : 

```
apt-get install libfftw3-3
apt-get install libfftw3-dev
```

However, still the issue persists, what is possibly causing this and how to resolve this ? Also is it possible to pass the path to `FFTW` while building?

**Comment by jacobkahn** [comment]
@shaheenkdr — you can pass `FFTW_LIBRARY` as an argument to CMake with the path to the FFTW lib. Did you confirm the library is somewhere in `/usr/`? I assume you're building on Ubuntu?

**Comment by shaheenkdr** [comment]
@jacobkahn I tried this :

```
cmake .. -DCMAKE_BUILD_TYPE=Release -DCRITERION_BACKEND=CUDA -DArrayFire_DIR=/opt/arrayfire-no-gl/share/ArrayFire/cmake/ -DFFTW_LIBRARY=/usr/local/lib/cmake/fftw3

```

Which gives the same error, any other way to resolve the issue?

**Comment by shaheenkdr** [comment]
> @shaheenkdr — you can pass `FFTW_LIBRARY` as an argument to CMake with the path to the FFTW lib. Did you confirm the library is somewhere in `/usr/`? I assume you're building on Ubuntu?

yeah I verified, the CMake config files are there

**Comment by jacobkahn** [comment]
@shaheenkdr — how do you have FFTW installed, and why is it in `/usr/local/lib/cmake/fftw3`? If you're setting `FFTW_LIBRARY`, it expects a path to the shared/static library. If you want to pass a path to a CMake config, you should use `FFTWDIR` or `FFTW_ROOT`.

**Comment by shaheenkdr** [comment]
@jacobkahn Can you just let me know where it installs by default , and what all files should be present in a directory that contains a successful installation of `FFTW` ? There are various files associated with `FFTW` seen in different directories under `/usr/` .  If I am to use `FFTW_LIBRARY` , can you let me know what kind of tree structure should the directory that I point to should contain ? Thank you.

**Comment by jacobkahn** [comment]
@shaheenkdr — on Ubuntu 16.04, when I run [`sudo apt-get install libfftw3-dev`](https://launchpad.net/ubuntu/+source/fftw3), `libfftw3.so`, `libfftw3f.so`, and `libfftw3l.so` (and many other FFTW libraries) appear in `/usr/lib/x86_64-linux-gnu/`, and FFTW headers appear in `/usr/include/` (for instance `/usr/include/fftw3.h`).

When I run `cmake` with wav2letter++, it finds FTW components without my needing to specify any flags at all (`FFTW_LIBRARY` or otherwise). I'd try building without any specified configuration at all.

**Comment by shaheenkdr** [comment]
@jacobkahn As you mentioned all files were in my directories as well, so I **resolved** this issue by removing the `build` directory in `wav2letters` directory and created a new build folder and executed CMAKE, that fixed the issue for me. Wholeheartedly Thanking you for helping out :)

**Comment by jacobkahn** [comment]
@shaheenkdr — glad you have it working! In general, CMake sometimes caches library and include paths, and removing your entire build directory of the location of dependencies changes can be a good strategy.

**Comment by bobblePandey** [comment]
@jacobkahn 
I am also stuck in the same issue while building it for ARM. I was successfully able to build FFTW for ARM and installed it at custom path.
Then tried passing the libraries to wav2letter cmake, but it's not accepting path from any variable that I tried to set.
It's strange that -DFFTW_INCLUDES variable is working fine and custom include path that I set is resolved, but for libraries I tried setting -DFFTW_ROOT, -DFFTWDIR, ENV$(FFTWDIR), -DFFTW_LIBRARY and all these variables didn't helped me out.

Can you please look into this, if I'm doing something wrong. Below is the snippet of the error:
Thanks in Advance.



`$ export FFTWDIR=/home/abhishek/office/speechRecognition/fftw-3.3.8/libs/lib/
abhishek@abhishek-hp-pavilion-x360-convertible-14-dh0xxx:~/office/speechRecognition/wav2letter/build$ 
abhishek@abhishek-hp-pavilion-x360-convertible-14-dh0xxx:~/office/speechRecognition/wav2letter/build$ 
abhishek@abhishek-hp-pavilion-x360-convertible-14-dh0xxx:~/office/speechRecognition/wav2letter/build$ /home/abhishek/Android/Sdk/cmake/3.6.4111459/bin/cmake .. -DFLASHLIGHT_BACKEND=CPU -DCMAKE_BUILD_TYPE=Release -DW2L_BUILD_LIBRARIES_ONLY=ON -DW2L_BUILD_INFERENCE=ON -DW2L_LIBRARIES_USE_CUDA=OFF -DCMAKE_TOOLCHAIN_FILE=/home/abhishek/Android/Sdk/ndk/20.1.5948944/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -DCBLAS_LIBRARIES=~/office/speechRecognition/OpenBLAS/build/lib/ -DFFTW_ROOT=/home/abhishek/office/speechRecognition/fftw-3.3.8/libs/ -DFFTWDIR=/home/abhishek/office/speechRecognition/fftw-3.3.8/libs/lib -DFFTW_INCLUDES=/home/abhishek/office/speechRecognition/fftw-3.3.8/libs/include -DFFTW_LIBRARY=/home/abhishek/office/speechRecognition/fftw-3.3.8/libs/lib/
-- ANDROID_PLATFORM not set. Defaulting to minimum supported version
16.
-- Checking for module 'cblas'
--   No package 'cblas' found
-- CBLAS library found
-- CBLAS found (include: , library: ~/office/speechRecognition/OpenBLAS/build/lib/)
CMake Error at /home/abhishek/Android/Sdk/cmake/3.6.4111459/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find FFTW (missing: FFTW_LIBRARIES)
Call Stack (most recent call first):
  /home/abhishek/Android/Sdk/cmake/3.6.4111459/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindFFTW.cmake:94 (find_package_handle_standard_args)
  src/libraries/feature/CMakeLists.txt:15 (find_package)


-- Configuring incomplete, errors occurred!
`

**Comment by WilliamTambellini** [comment]
Got the same issue with cmake 3.13 when building flashlight master now using the cmake scripts from w2l.
The .pc seems correct:

$more /usr/lib/x86_64-linux-gnu/pkgconfig/fftw3.pc
prefix=/usr
exec_prefix=${prefix}
libdir=${prefix}/lib/x86_64-linux-gnu
includedir=${prefix}/include
Name: FFTW
Description: fast Fourier transform library
Version: 3.3.4
Libs: -L${libdir} -lfftw3 
Libs.private: -lm
Cflags: -I${includedir}

pkg-config correctly finds the module:
$ pkg-config --list-all | grep fftw
fftw3                          FFTW - fast Fourier transform library
fftw3f                         FFTW - fast Fourier transform library
fftw3l                         FFTW - fast Fourier transform library
fftw3q                         FFTW - fast Fourier transform library
cufftw-10.2                    cufftw - CUDA Fast Fourier Transform Wide

but both ${PKG_FFTW_LIBRARY_DIRS} and ${PKG_FFTW_INCLUDE_DIRS} are empty so find fftw fails so cmake fails.

I m suspecting that the behavior depends on the version of cmake.
According to 
https://cmake.org/cmake/help/v3.13/module/FindPkgConfig.html
cmake seems to sometimes define YYY_LIBDIR and YYY_INCLUDEDIR
which are indeed non empty in my case.

Easy fix in FindFFTW.cmake:

  if(NOT PKG_FFTW_LIBRARY_DIRS)
    set(PKG_FFTW_LIBRARY_DIRS ${PKG_FFTW_LIBDIR})
    set(PKG_FFTW_INCLUDE_DIRS ${PKG_FFTW_INCLUDEDIR})
  endif()

@jacobkahn  worth a PR in flashlight ?

**Comment by jacobkahn** [comment]
@WilliamTambellini absolutely worth it - please do send one! Thanks for digging a bit deeper.

**Comment by tensorfoo** [comment]
I've build fftw under flashlight/fftw-3.3.9 and tried setting all of FFTW3_ROOT, FFTW3_LIBRARY etc to this directory. I still get Could NOT find FFTW3 (missing: FFTW3_DIR).  I don't have root access to install packages. Any suggestions?

**Comment by Dari0GR** [comment]
tengo el siguiente problema, podrian ayudarme por favor:

CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Could NOT find FFTW (missing: FFTW_LIBRARIES FFTW_INCLUDE_DIRS)
CMake Warning at CMakeLists.txt:95 (message):
  FFTW library not available.  Some targets will not be built


-- Configuring done
-- Generating done
-- Build files have been written to: /Users/dariogr/Desktop/kbd-audio/build
